### ISSUE TITLE
Some generic feedback on your bundle

### ISSUE THREAD

**Issue by iltar** [faustbrian/ARK-Symfony#2]
I came here through a blog post (purely out of curiosity) and would like to provide some feedback.

First of all, there are some terms being used that all mean something else, I would recommend to use one term only to describe the same.
 - Repository name: `faustbrian/ARK-Symfony`
 - Composer package: `faustbrian/ark-symfony`
 - Composer description: `An ARK bridge for Symfony.`
 - Source code only contains a Bundle

Based on what I found in your package, I would call it a Symfony Bundle, but the repository and composer name make me believe that it's an application. The composer description however, merely states it's a bridge between Symfony and ARK.

My recommendation
 - Rename the repository to: `faustbrian/ark-bundle`
 - Rename the Composer package to: `faustbrian/ark-bundle`
 - Change the description to something like `Provides ARK integration in Symfony.`
 - Add the `bundle` keyword to your composer.json

Hopefully this will give developers a clear insight on what this repository contains.

---

Second, I would like to propose a small BC break in your bundle. You have put some effort into making the configuration different from the defaults, that means it requires extra configuration:
https://github.com/faustbrian/ARK-Symfony/blob/e071621263cad89c9842ea6972bf1bd920253f75/src/ArkBundle.php#L26-L33

I propose to remove this function and simply use the parent variant. That means that your extension will be called `ArkExtension` instead, and your configuration key will simply be `ark`. Symfony Bundles usually provide the config keys and it's not really needed to include the `bundle` keyword in here.

---

Third. With the second suggestion in mind, you can change the service definitions to from `ark_bundle.config` and `ark_bundle.client` to `ark.config` and `ark.client`. Maybe even better, give them a Fully Qualified Class Name as service id and simply use the above suggestion as alias to the FQCN variant. This means it will play a lot better with autowiring. I also saw that your services are defined as public services, that would be kind of a show stopper for me. There's absolutely no reason to have them public, other than having access to them by using a service locator (`Container::get()`), which can be completely avoided by injecting the dependencies (with autowiring for example).

---

Fourth. I've noticed that you store the arguments of your service in parameters. I think this is a bad idea, because you don't need them more than once. Instead of defining them as parameters and then having the container get the parameter values each time the service is required, I would rather see that your Extension class sets the arguments of your service definition directly. Example:
```php
$configDefinition = $container->getDefinition(Config::class);
$configDefinition->setArgument('$ip', $config['ip']);
$configDefinition->setArgument('$port', $config['port']);
// etc
```

This gives the same benefit as not making services public, smaller container and more optimizations that improve your run-time performance. It also means that other services can't "steal" the information.

**Comment by faustbrian** [comment]
Feel free to send a PR for your recommended changes except the renaming as the name of the package will stay how it is for now.
